// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "miles":return img`
........................
........................
........................
........................
........................
........................
........................
........................
.............f..........
............fff.........
...........fffff........
..........fffffff.......
.........f2222222f......
.........f2112112f......
.........f2212122f......
.........f2222222f......
.........fffffffff......
..........f2f2f2f.......
....fff....f222f..ff....
...ffffffff22222fffff...
....fff....f222f..ff....
...........2f2f2........
..........f.....f.......
..........f.....f.......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
